version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: demo-db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    ports:
      - '6432:5432'

  backend:
    build:
      context: .
    ports:
      - '8100:8100'
    command: java -jar bia-assignment-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo-db
      - SPRING_PROFILES_ACTIVE=dev

